packages:
  - "packages/*"
allowBuilds:
  better-sqlite3: true
  esbuild: true
  bufferutil: false
  utf-8-validate: false
  bigint-buffer: true
  sharp: true
  "@tailwindcss/oxide": true
  unrs-resolver: true
  '@stellar/stellar-sdk': false
  blake-hash: false
  protobufjs: false
  tiny-secp256k1: false
  usb: false
